name: Build Docker Image

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build and upload the website docker image
        env:
          CONTAINER_URL: docker.pkg.github.com/${{github.repository}}/
        run: |
          echo ${{secrets.GITHUB_TOKEN}} | docker login --username $GITHUB_ACTOR --password-stdin docker.pkg.github.com
          export SHORT_SHA=`git rev-parse --short=7 ${GITHUB_SHA}`
          docker build . --file Dockerfile --build-arg BUILD_VERSION=${SHORT_SHA} --tag ${CONTAINER_URL}website:${SHORT_SHA} --tag ${CONTAINER_URL}website:latest
          docker push ${CONTAINER_URL}website:${SHORT_SHA}
          docker push ${CONTAINER_URL}website:latest
      - name: Trigger deployment webhook
        env:
          CONTAINER_URL: docker.pkg.github.com/${{github.repository}}/
        run: |
          export SHORT_SHA=`git rev-parse --short=7 ${GITHUB_SHA}`
          curl -X POST -H "Content-Type: application/json" --data "{ \"name\": \"${CONTAINER_URL}website\", \"tag\": \"${SHORT_SHA}\" }" https://keel.iteralis.com/v1/webhooks/native
      - name: Immediately purge CloudFlare cache
        run: |
          curl -X POST "https://api.cloudflare.com/client/v4/zones/f0d1494c3461ef07e5876c87454b5427/purge_cache" -H "Authorization: Bearer ${{secrets.CLOUDFLARE_API_TOKEN}}" -H "Content-Type: application/json" --data '{"purge_everything":true}'
      - name: Wait for fifteen seconds for deployment to activate
        run: sleep 15s
      - name: Purge CloudFlare cache again after deployment complete
        run: |
          curl -X POST "https://api.cloudflare.com/client/v4/zones/f0d1494c3461ef07e5876c87454b5427/purge_cache" -H "Authorization: Bearer ${{secrets.CLOUDFLARE_API_TOKEN}}" -H "Content-Type: application/json" --data '{"purge_everything":true}'
